name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [ checks_requested ]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "test"
        shell: bash

  auto-merge:
    needs:
      - test
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    # if: ${{ always() && !cancelled() && !failure() && github.actor == 'dependabot[bot]' }}
    steps:
      - run: gh pr merge --rebase --auto "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
